import Foundation
import ORModels

/// Keeps a calibration between runs, as bytes (AC-FR-S-C-2-2, AC-FR-S-C-2-8).
///
/// **A file rather than a SwiftData column, and rather than `UserDefaults`.** The store's
/// schema is versioned and migrated (`RunStoreSchema`), and a calibration whose *encoded
/// shape belongs to another package* has no business in it — S-064 will change that shape,
/// and a schema migration is a heavy price for a value that can be regenerated by running
/// a hundred metres. `UserDefaults` was the other candidate and loses on a different point:
/// it is backed up and restored between devices, and a calibration fitted to one phone's
/// accelerometer in one runner's hand is not a thing to carry to a new phone silently.
///
/// One file per carry position, because a calibration learned hand-held says nothing about
/// a pocketed phone (ADR-S-04). The day a second position exists its calibration starts
/// empty rather than inheriting a number fitted to a different mechanical system.
public final class CalibrationFileStore: CalibrationStoring, @unchecked Sendable {

    private let directory: URL
    private let fileManager: FileManager
    private let lock = NSLock()

    public init(directory: URL, fileManager: FileManager = .default) {
        self.directory = directory
        self.fileManager = fileManager
        try? fileManager.createDirectory(at: directory, withIntermediateDirectories: true)
    }

    /// The app's own Application Support directory.
    public static func inApplicationSupport(
        fileManager: FileManager = .default
    ) -> CalibrationFileStore {
        let base = fileManager.urls(for: .applicationSupportDirectory, in: .userDomainMask)
            .first ?? fileManager.temporaryDirectory
        return CalibrationFileStore(
            directory: base.appendingPathComponent("StandaloneCalibration", isDirectory: true),
            fileManager: fileManager)
    }

    public func loadCalibration(for position: CarryPosition) -> Data? {
        lock.lock(); defer { lock.unlock() }
        return try? Data(contentsOf: url(for: position))
    }

    public func saveCalibration(_ payload: Data?, for position: CarryPosition) {
        lock.lock(); defer { lock.unlock() }
        let destination = url(for: position)
        guard let payload else {
            // AC-FR-S-C-2-8's reset. Deleting rather than writing empty bytes, because
            // `CalibrationBridge` reads unreadable bytes as "no calibration" — so an empty
            // file would work by accident, and working by accident is how a later change
            // to that decoder quietly resurrects a reset calibration.
            try? fileManager.removeItem(at: destination)
            return
        }
        // Atomic, for the same reason the sample store's flush is: a crash mid-write must
        // leave the previous calibration intact rather than a truncated one, and a
        // truncated calibration is indistinguishable from a corrupt one — which costs the
        // runner the first hundred metres of their next run.
        try? payload.write(to: destination, options: .atomic)
    }

    /// Whether anything is stored, without decoding it. Backs the settings screen's
    /// "not calibrated yet" state without needing the estimator.
    public func hasCalibration(for position: CarryPosition) -> Bool {
        lock.lock(); defer { lock.unlock() }
        return fileManager.fileExists(atPath: url(for: position).path)
    }

    private func url(for position: CarryPosition) -> URL {
        directory.appendingPathComponent("\(position.rawValue).calibration")
    }
}
